# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Nodejs  
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.1.0
      
      # Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build

      # Copy index.html to 404.html for GitHub Pages SPA support
      - name: Handle 404 for SPA
        run: cp dist/index.html dist/404.html

      # Deploy to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist